import "@/app/globals.css";
import { Outfit } from "next/font/google";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
	title: "E-Cjenovnik - Dashboard",
	// description: 'Generated by create next app',
};

export default function RootLayoutAdmin({ children }) {
	return (
		<html lang="sr">
			<body className={outfit.className}>{children}</body>
		</html>
	);
}
