import "@/app/globals.css";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import { Outfit } from "next/font/google";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
	title: "E-Cjenovnik",
	// description: 'Generated by create next app',
};

export default function RootLayoutUser({ children }) {
	return (
		<html lang="sr">
			<body
				className={cn(
					"flex flex-col min-h-screen-custom bg-gray-200 text-gray-900 dark:bg-gray-950 dark:text-gray-300 transition-colors duration-300 " +
						outfit.className
				)}
			>
				{children}

				<Footer />
			</body>
		</html>
	);
}
